### ISSUE TITLE
Feature request: Markup

### ISSUE THREAD

**Issue by karstenspang** [mikaello/avrodoc-plus#14]
It would be nice to be able to use at least some level of markup in the doc field of the avsc. It could be as simple as putting ```white-space: pre-line``` or ```white-space: pre-wrap``` in the CSS, controlled by an option. I must admit that I cannot figure where to put it in the existing less files, or fix it using the ```-s``` option.
For example, the doc generated from my existing avdl file, results in this line in the avsc:
```
"doc" : "Severity level of the message.\nValues:\n\t0 Error\n\t1 Warn\n\t2 Info\n\t3 Debug\n\t4 Trace"
```
If that came out as
```
Severity level of the message.
Values:
    0 Error
    1 Warn
    2 Info
    3 Debug
    4 Trace
```
it would suffice for me. I mean, it shouldn't be monospace, I hope you get the idea.

**Comment by mikaello** [comment]
You have the power of Markdown, although it is an quite old flavor used in this library: https://github.com/cadorn/markdown-js

I have honestly never used the `-s` option myself, that is a remnant from the previous fork. But my impression is that it is for the overall look of the site, not the content of the `doc` fields, that would be the responsibility of Markdown.

**Comment by karstenspang** [comment]
Great! Just what I need, thanks.
